#
# ================================================
# * QQ OpenAPI for java
# ================================================
# * QQ Connect settings
#  

#APP_ID
APP_ID = 100240682

#APP_KEY
APP_KEY = 06c8c3f91c3bc1bf0df88258cff33660

#OAUTH_CALLBACK
OAUTH_CALLBACK = http://www.nextapp.cn/action/openid/login