
error_reporter=no-reply@oschina.net,
administrator=zhl@oschina.net,ld@oschina.net

accounts=smtp

# Email Sender Account
smtp.administrator=ld@oschina.net
smtp.editor=ld@oschina.net
smtp.hostname=mail.oschina.net
smtp.port=25
smtp.ssl=false
smtp.username=no-reply
smtp.password=0sch1na123
smtp.sender=NextApp.CN:no-reply@oschina.net
smtp.interval=10

# Email Sender Account
smtp_backup.administrator=ld@oschina.net
smtp_backup.editor=ld@oschina.net
smtp_backup.hostname=smtp.gmail.com
smtp_backup.port=465
smtp_backup.ssl=true
smtp_backup.username=oschina.net@gmail.com
smtp_backup.password=oschina123
smtp_backup.sender=NextApp.CN:oschina.net@gmail.com
smtp_backup.interval=100